name: Create translation info

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
        restore-keys: |
          ${{ runner.os }}-
    
    - name: Install Python
      uses: actions/setup-python@v2

    - name: Install babel
      run: python -m pip install Babel
      
    - name: Update translation info
      run: python create_translation_info.py
      
    - name: Commit updated
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update translation info
